##board manager
#tells platformio to use the espressif32 platform and the esp32-s3-devkitc-1 board
[env:freenove_esp32s3] #creates  build environment named esp32s3
platform = espressif32 #use esp32 compiler
board = freenove_esp32_s3_wroom #specific board definition
framework = arduino ##has to be arduino framework cos the micro_ros_plat formio component uses it
 
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    https://github.com/micro-ROS/micro_ros_platformio
    ## switch to https://github.com/micro-ROS/micro_ros_espidf_component for espidf framework
board_microros_distro = humble
board_microros_transport = serial